"""Finds code addresses referenced only indirectly (data pointers, lis/addi
pairs) that rexglue's analysis did not register as functions, and writes
[functions] entries for them. Python port of FindMissingFuncs.cs (from the
Outpost Kaloki X / King Kong ports) that handles code split over several
sections (.xidata code, .text, .embsec_).

  python tools/find_missing_funcs.py   (after a codegen run; needs ewj/image.bin)
"""
import bisect, json, os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from ppcdis import BASE, IMG, u32

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'ewj')
GEN = os.path.join(ROOT, 'generated', 'default')
CODE = [(0x826F0000, 0x827E55C0), (0x82819A00, 0x8382C467)]  # import thunks 0x827E55C0.. excluded
CODE_END = 0x8382C467

def in_code(a):
    return (a & 3) == 0 and any(lo <= a < hi for lo, hi in CODE)

def is_terminator(w):
    return w in (0x4E800020, 0x4E800420, 0) or ((w >> 26) == 18 and (w & 3) == 0)

def main():
    known = {int(k, 16) for k in re.findall(r'"([0-9A-F]{8})"\s*:', open(os.path.join(GEN, 'codegen.partition.json')).read())}
    labels = set()
    for f in os.listdir(GEN):
        if '_recomp.' in f and f.endswith('.cpp'):
            labels.update(int(x, 16) for x in re.findall(r'^loc_([0-9A-F]{8}):', open(os.path.join(GEN, f)).read(), re.M))
    refs = {}
    # 1. pointers in data (everything outside the code ranges)
    for a in range(BASE, BASE + len(IMG) - 3, 4):
        if any(lo <= a < hi for lo, hi in CODE):
            continue
        v = u32(a)
        if in_code(v):
            refs.setdefault(v, f'data ptr @0x{a:08X}')
    # 2. lis rX,hi ; addi/ori rY,rX,lo in code
    for lo_, hi_ in CODE:
        lis = [None] * 32
        for a in range(lo_, hi_, 4):
            w = u32(a); op = w >> 26; rd = (w >> 21) & 31; ra = (w >> 16) & 31
            if op == 15 and ra == 0:
                lis[rd] = ((w & 0xFFFF) << 16) & 0xFFFFFFFF
                continue
            if op in (14, 24) and lis[ra] is not None:
                lo = w & 0xFFFF
                v = (lis[ra] + (lo - 0x10000 if lo & 0x8000 else lo)) & 0xFFFFFFFF if op == 14 else lis[ra] | lo
                if in_code(v):
                    refs.setdefault(v, f'lis/addi @0x{a:08X}')
            if is_terminator(w):
                lis = [None] * 32
    cands = sorted(t for t in refs if t not in known and t not in labels and is_terminator(u32(t - 4)) and u32(t) != 0)
    starts = sorted(known | set(cands))
    out = ['# Auto-generated by tools/find_missing_funcs.py - functions only referenced indirectly.', '[functions]']
    for c in cands:
        i = bisect.bisect_right(starts, c)
        nxt = starts[i] if i < len(starts) else CODE_END
        end = c
        while end < nxt and u32(end) != 0:
            end += 4
        out.append(f'0x{c:08X} = {{ end = 0x{end:08X} }}  # {refs[c]}')
    open(os.path.join(ROOT, 'missing_funcs.toml'), 'w').write('\n'.join(out) + '\n')
    print(f'known={len(known)} labels={len(labels)} code-refs={len(refs)} missing={len(cands)}')
    print('0x82796560 found:', any(c == 0x82796560 for c in cands))

main()
