"""Registers every long-branch veneer ('lis r11,hi; addi r11,r11,lo; mtctr r11;
bctr') and its target as a function. The linker placed two identical tables of
them (in .xidata and in an .embsec_ section) and the game takes function
pointers to the veneers (thread entries, callbacks), so each one must be
callable through the function table."""
import os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from ppcdis import u32, pdata_starts

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'ewj')
RANGES = [(0x826F0000, 0x827E55C0), (0x83658000, 0x8382C467)]

veneers, targets = {}, set()
for lo, hi in RANGES:
    for a in range(lo, hi, 4):
        w = u32(a)
        if (w >> 16) == 0x3D60 and (u32(a + 4) >> 16) == 0x396B and u32(a + 8) == 0x7D6903A6 and u32(a + 12) == 0x4E800420:
            l = u32(a + 4) & 0xFFFF
            t = (((w & 0xFFFF) << 16) + (l - 0x10000 if l & 0x8000 else l)) & 0xFFFFFFFF
            veneers[a] = t
            targets.add(t)
# Targets that are themselves veneers are already covered, and import thunks
# (0x827E55C0-0x82819875) are bound by the runtime, not declared here.
targets -= set(veneers)
targets = {t for t in targets if not 0x827E55C0 <= t < 0x82819875}
# A few veneers point at data (e.g. 0x8385C3AC); the runtime only maps code.
targets = {t for t in targets if 0x826F0000 <= t < 0x8382C467}
have = set()
for f in ('overrides.toml', 'missing_funcs.toml', 'tailcall_funcs.toml', 'thunk_funcs.toml'):
    p = os.path.join(ROOT, f)
    if os.path.exists(p):
        have.update(int(m, 16) for m in re.findall(r'^(0x[0-9A-Fa-f]{8})\s*=', open(p).read(), re.M))
# .pdata functions keep their .pdata extent (it covers SEH funclets).
have |= pdata_starts()
out = ['# Auto-generated by tools/find_veneers.py: long-branch veneers and their targets.', '[functions]']
out += [f'0x{a:08X} = {{ size = 16 }}' for a in sorted(veneers) if a not in have]
out += [f'0x{t:08X} = {{}}  # veneer target' for t in sorted(targets) if t not in have]
open(os.path.join(ROOT, 'veneer_funcs.toml'), 'w').write('\n'.join(out) + '\n')
print(f'{len(veneers)} veneers, {len(targets)} distinct targets, {len(out) - 2} entries written')
