"""Finds C++ this-adjusting thunks ('addi r3,r3,N' then 'b target') in the
executable sections of the dumped image and writes every thunk and its target
as a [functions] entry. The analyzer treats a run of these 8-byte thunks as
one function and resolves only one target per codegen pass."""
import os, re, struct, sys
sys.path.insert(0, os.path.dirname(__file__))
from ppcdis import BASE, IMG, u32, pdata_starts

# Executable ranges (from `rexglue --log-level debug codegen`): .xidata code
# up to the import thunks, .text, and the .embsec_ sections.
RANGES = [(0x826F0000, 0x827E55C0), (0x82819A00, 0x83658000), (0x83658000, 0x8382C467)]

def known_entries(paths):
    s = set()
    for p in paths:
        if os.path.exists(p):
            for m in re.finditer(r'^(0x[0-9A-Fa-f]{8})\s*=', open(p).read(), re.M):
                s.add(int(m.group(1), 16))
    return s

def main(out):
    found = {}
    for lo, hi in RANGES:
        for a in range(lo, hi - 4, 4):
            w0, w1 = u32(a), u32(a + 4)
            # addi r3, r3, simm  (opcode 14, rD=3, rA=3)
            if (w0 >> 16) != 0x3863:
                continue
            # Not reachable by falling through: the word before is an
            # unconditional branch, blr, a trap or padding.
            prev = u32(a - 4)
            if not ((prev >> 26) == 18 and (prev & 1) == 0 or prev == 0x4E800020 or prev == 0 or (prev >> 26) == 3):
                continue
            # b target (opcode 18, AA=0, LK=0)
            if (w1 >> 26) != 18 or (w1 & 3) != 0:
                continue
            off = w1 & 0x03FFFFFC
            if off & 0x02000000:
                off -= 0x04000000
            target = (a + 4 + off) & 0xFFFFFFFF
            if not any(l <= target < h for l, h in RANGES):
                continue
            found[a] = f'thunk -> 0x{target:08X}'
            found.setdefault(target, f'thunk target from 0x{a:08X}')
    ewj = os.path.join(os.path.dirname(__file__), '..', 'ewj')
    have = known_entries([os.path.join(ewj, f) for f in ('overrides.toml', 'missing_funcs.toml', 'tailcall_funcs.toml')])
    have |= pdata_starts()  # keep their .pdata extent (it covers SEH funclets)
    new = {a: c for a, c in sorted(found.items()) if a not in have}
    with open(out, 'w') as f:
        f.write('# Auto-generated by tools/find_thunks.py: this-adjusting thunks and their targets.\n[functions]\n')
        for a, c in new.items():
            f.write(f'0x{a:08X} = {{}}  # {c}\n')
    print(f'{len(found)} thunk entries/targets, {len(new)} new')

main(sys.argv[1])
